name: Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    - name: Build the Images
      working-directory: ${{github.workspace}}
      run: make images

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.7.0
      with:
        config: ingress/cluster.yml

    - name: Deploy
      run: bash ci/do_ci.sh
